/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:7b484bcb-562b-42ef-825c-3cfdf80390de",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_B9AGNEmZv",
    "aws_user_pools_web_client_id": "2j4dd3qi04jo3st9k9mui5jq0u",
    "oauth": {        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/",
        "redirectSignOut": "http://localhost:3000/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "authorize-mvp-storage121345-dev",
    "aws_user_files_s3_bucket_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://flfau7kic5a53jhq7qiizrs6cy.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-a5weuugbc5bqtlebm5rn72ez5i"
};


export default awsmobile;
